INFO 2024-04-22 15:02:41,654 autoreload 13948 13968 Watching for file changes with StatReloader
INFO 2024-04-22 15:03:15,764 basehttp 13948 3876 "GET /games/coin/ HTTP/1.1" 200 8
INFO 2024-04-22 15:03:17,676 basehttp 13948 3876 "GET /games/coin/ HTTP/1.1" 200 8
INFO 2024-04-22 15:03:22,039 basehttp 13948 3876 "GET /games/coin/ HTTP/1.1" 200 10
INFO 2024-04-22 15:03:36,729 basehttp 13948 3876 "GET /games/cube/ HTTP/1.1" 200 1
INFO 2024-04-22 15:03:40,520 basehttp 13948 3876 "GET /games/cube/ HTTP/1.1" 200 1
INFO 2024-04-22 15:03:44,051 basehttp 13948 3876 "GET /games/number/ HTTP/1.1" 200 2
INFO 2024-04-22 15:03:57,888 basehttp 13948 3876 "GET / HTTP/1.1" 200 40
INFO 2024-04-22 15:03:58,915 basehttp 13948 3876 "GET / HTTP/1.1" 200 40
INFO 2024-04-22 15:31:44,461 autoreload 8516 2520 Watching for file changes with StatReloader
INFO 2024-04-22 15:31:45,800 basehttp 8516 10284 "GET / HTTP/1.1" 200 40
INFO 2024-04-22 15:32:50,558 basehttp 8516 10284 "GET /games/cube/ HTTP/1.1" 200 1
INFO 2024-04-22 15:35:07,778 basehttp 8516 10284 "GET /games/cube/ HTTP/1.1" 200 1
INFO 2024-04-23 14:20:51,363 autoreload 14664 9968 Watching for file changes with StatReloader
INFO 2024-04-23 14:21:32,935 autoreload 14664 9968 D:\Django_education_seminars\mydjangoproject\gamesapp\views.py changed, reloading.
INFO 2024-04-23 14:21:33,224 autoreload 9520 14752 Watching for file changes with StatReloader
INFO 2024-04-23 14:21:34,781 basehttp 9520 7856 "GET / HTTP/1.1" 200 40
ERROR 2024-04-23 14:21:46,158 log 9520 7856 Internal Server Error: /games/coin/
Traceback (most recent call last):
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: table gamesapp_coin has no column named result

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\mydjangoproject\gamesapp\views.py", line 13, in coinflip
    value = models.Coin.objects.create(result=random.choice(['Орел', 'Решка']), time=datetime.now())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: table gamesapp_coin has no column named result
ERROR 2024-04-23 14:21:46,162 basehttp 9520 7856 "GET /games/coin/ HTTP/1.1" 500 157043
INFO 2024-04-23 14:23:11,918 autoreload 9520 14752 D:\Django_education_seminars\mydjangoproject\gamesapp\models.py changed, reloading.
INFO 2024-04-23 14:23:12,200 autoreload 192 14400 Watching for file changes with StatReloader
ERROR 2024-04-23 14:23:15,288 log 192 7276 Internal Server Error: /games/coin/
Traceback (most recent call last):
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\mydjangoproject\gamesapp\views.py", line 13, in coinflip
    value = models.Coin.objects.create(result=random.choice(['Орел', 'Решка']), time=datetime.now())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: Coin() got unexpected keyword arguments: 'result'
ERROR 2024-04-23 14:23:15,290 basehttp 192 7276 "GET /games/coin/ HTTP/1.1" 500 83961
INFO 2024-04-23 14:23:42,903 autoreload 192 14400 D:\Django_education_seminars\mydjangoproject\gamesapp\views.py changed, reloading.
INFO 2024-04-23 14:23:43,203 autoreload 13360 3172 Watching for file changes with StatReloader
INFO 2024-04-23 14:23:44,463 basehttp 13360 9648 "GET /games/coin/ HTTP/1.1" 200 10
INFO 2024-04-23 14:23:46,598 basehttp 13360 9648 "GET /games/coin/ HTTP/1.1" 200 10
INFO 2024-04-23 14:23:47,563 basehttp 13360 9648 "GET /games/coin/ HTTP/1.1" 200 8
INFO 2024-04-23 14:23:47,840 basehttp 13360 9648 "GET /games/coin/ HTTP/1.1" 200 8
INFO 2024-04-23 14:24:07,918 basehttp 13360 9648 "GET /games/coin/ HTTP/1.1" 200 10
INFO 2024-04-23 14:24:08,310 basehttp 13360 9648 "GET /games/coin/ HTTP/1.1" 200 10
INFO 2024-04-23 14:24:59,367 autoreload 13360 3172 D:\Django_education_seminars\mydjangoproject\gamesapp\models.py changed, reloading.
INFO 2024-04-23 14:24:59,636 autoreload 1296 11980 Watching for file changes with StatReloader
INFO 2024-04-23 14:26:06,535 autoreload 1296 11980 D:\Django_education_seminars\mydjangoproject\gamesapp\models.py changed, reloading.
INFO 2024-04-23 14:26:06,802 autoreload 11116 968 Watching for file changes with StatReloader
INFO 2024-04-23 14:26:11,742 basehttp 11116 6380 "GET /games/coin/ HTTP/1.1" 200 8
ERROR 2024-04-23 14:26:14,137 log 11116 6380 Internal Server Error: /games/last/
Traceback (most recent call last):
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\mydjangoproject\gamesapp\views.py", line 27, in get_last_n_coins
    return models.Coin.get_last_n_coins(n)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\mydjangoproject\gamesapp\models.py", line 14, in get_last_n_coins
    return Coin.objects.order_by('-time')[:n]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\models\query.py", line 428, in __getitem__
    or (k.stop is not None and k.stop < 0)
                               ^^^^^^^^^^
TypeError: '<' not supported between instances of 'WSGIRequest' and 'int'
ERROR 2024-04-23 14:26:14,139 basehttp 11116 6380 "GET /games/last/ HTTP/1.1" 500 75221
INFO 2024-04-23 14:29:21,687 autoreload 11116 968 D:\Django_education_seminars\mydjangoproject\gamesapp\views.py changed, reloading.
INFO 2024-04-23 14:29:21,971 autoreload 11996 2872 Watching for file changes with StatReloader
ERROR 2024-04-23 14:29:22,588 log 11996 12332 Internal Server Error: /games/last/
Traceback (most recent call last):
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\middleware\clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django_education_seminars\venv\Lib\site-packages\django\db\models\query.py", line 1488, in _filter_or_exclude
    raise TypeError("Cannot filter a query once a slice has been taken.")
TypeError: Cannot filter a query once a slice has been taken.
ERROR 2024-04-23 14:29:22,590 basehttp 11996 12332 "GET /games/last/ HTTP/1.1" 500 81818
INFO 2024-04-23 14:31:13,610 autoreload 11996 2872 D:\Django_education_seminars\mydjangoproject\gamesapp\views.py changed, reloading.
INFO 2024-04-23 14:31:13,883 autoreload 9868 3212 Watching for file changes with StatReloader
INFO 2024-04-23 14:31:16,581 basehttp 9868 14940 "GET /games/last/ HTTP/1.1" 200 209
INFO 2024-04-23 14:48:22,709 autoreload 13884 10404 Watching for file changes with StatReloader
INFO 2024-04-23 14:49:42,744 autoreload 4420 10680 Watching for file changes with StatReloader
INFO 2024-04-23 14:51:17,245 autoreload 1968 9072 Watching for file changes with StatReloader
INFO 2024-04-23 14:51:18,768 basehttp 1968 14380 "GET / HTTP/1.1" 200 40
INFO 2024-04-23 14:51:27,348 basehttp 1968 14380 "GET /blog HTTP/1.1" 301 0
INFO 2024-04-23 14:51:27,361 basehttp 1968 10548 "GET /blog/ HTTP/1.1" 200 39
INFO 2024-04-23 14:51:48,934 autoreload 1968 9072 D:\Django_education_seminars\mydjangoproject\blogapp\views.py changed, reloading.
INFO 2024-04-23 14:51:49,213 autoreload 8944 14328 Watching for file changes with StatReloader
